# Uncomment this line to define a global platform for your project
platform :ios, '9.2'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'PhunwareWeather' do

pod 'OpenWeatherMapAPI', '~> 0.0.5'
pod 'MBProgressHUD', '~> 0.9.2'

end

